### ISSUE TITLE
运行main文件出现问题

### ISSUE THREAD

**Issue by Liu-Dakang** [SwimmingLiu/YOLOSHOW#2]
Traceback (most recent call last):
  File "E:\pythonProjects\YOLOSHOW-master\main.py", line 3, in <module>
    from YOLOSHOW import *
  File "E:\pythonProjects\YOLOSHOW-master\YOLOSHOW.py", line 38, in <module>
    formType, baseType = loadUiType(r"./ui\YOLOSHOWUI.ui")
TypeError: cannot unpack non-iterable NoneType object

**Comment by SwimmingLiu** [comment]
1. 如果没有修改ui文件，直接重启Pycharm / conda 环境即可
2. 如果修改了ui文件，请仔细检查修改是否有误

**Comment by Liu-Dakang** [comment]
好的，尝试了一下，重启pycharm未解决，需要使用conda命令行运行。
